---

domain: kit.edu

iprange:
  internal: "192.168.0.0/24"
  external: "192.168.1.0/24"

nonunique_ips:
  - 192.168.1.5

hostlistdir: hostlists/
builddir: build/

dhcp:
  build: dhcpd-hosts.conf.myserver.abc.kit.edu
  build_internal: dhcpd-hosts.conf.myserver2.abc.kit.edu

deployhosts:
  - 'myserver.abc.kit.edu'
  - 'myserver2.abc.kit.edu'

munin:
  inventory: munin/hosts
  build: muninhosts

hosts:
  build: hosts

ssh:
  build: ssh_known_hosts
  import: /etc/ssh/ssh_known_hosts
