#!/usr/bin/env python3

import argparse
import logging
import hostlist
from output_services import AnsibleOutput


def parse_args():
    parser = argparse.ArgumentParser(description='output ansible inventory')

    parser.add_argument('--verbose',
                        '-v',
                        action='count',
                        help='more output',
                        default=0)
    parser.add_argument('--list', action='store_true', default=True, help='List instances (default: True)')

    args = parser.parse_args()
    return args


def run():
    logging.basicConfig(format='%(levelname)s:%(message)s')

    logging.getLogger().setLevel(logging.WARNING)
    args = parse_args()
    if args.verbose >= 1:
        logging.getLogger().setLevel(logging.DEBUG)

    myhostlist = hostlist.YMLHostlist()

    logging.info("running make_ansible")
    ansible_inventory = AnsibleOutput.gen_content(myhostlist)

    print(ansible_inventory)

if __name__ == "__main__":
    run()
